<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App"></FrameworkReference>
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinForms" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
  </ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\LogicaCompartida\LogicaCompartida.csproj" />
	</ItemGroup>

</Project>